// Implement on OpenMp program to generate an array of random integers using single construct.
// Then use the parallel for directive to compute the square of each element.
// Display the Thread ID that generates the array and the Thread IDs procesing the elements
#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

#define N 5


int main() {
    int a[N], sq[N];
    printf("Name: Chirag Rao KV\n");
    printf("REG: 240962180\n");
    #pragma omp parallel
    {
        #pragma omp single
        {
            printf("Generated by Thread %d\n", omp_get_thread_num());
            for(int i=0;i<N;i++){
                a[i]=rand()%100;
                printf("%d\t",a[i]);
            }
        }
        #pragma omp for
        for(int i=0;i<N;i++) {
            sq[i]=a[i]*a[i];
            printf("\n%d*%d = %d  by Thread %d",a[i],a[i],sq[i], omp_get_thread_num());
        }
    }
    return 0;
}